#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/lib

PKG_NAME=Docker-GitLab
PKG_SHORT=gitlab
ETC_PATH="/var/packages/$PKG_NAME/etc"
TARGET_PATH="/var/packages/$PKG_NAME/target"
SHARE_PATH="$(synoshare --get docker | grep $'\t Path' | sed 's/.*\[\(.*\)].*/\1/')"
DOCKER_HOST=$(ip address show docker0 | grep inet | awk '{print $2}' | cut -f1 -d/ | head -n 1)
GITLAB_NAME=synology_gitlab
GITLAB_PROFILE="$TARGET_PATH"/config/synology_gitlab
REDIS_NAME=synology_gitlab_redis
REDIS_PROFILE="$TARGET_PATH"/config/synology_gitlab_redis

if [ "$SYNOPKG_TEMP_LOGFILE" ]; then
	log() {
		local text="$1"
		local idx=0
		shift 1
		for val in "$@"; do
			text="${text/\{$idx\}/$val}"
			let idx=1+$idx
		done
		echo "$text" >> $SYNOPKG_TEMP_LOGFILE
	}
fi

quote_sed() {
	sed -e 's|\\|\\\\|g' -e 's|&|\\\&|g' -e 's|/|\\/|g'
}

quote_sql() {
	sed -e "s|\`|\`\`|g"
}

quote_sh() {
	sed -e 's|\\|\\\\|g' -e 's|\"|\\\"|g' -e 's|`|\\`|g' -e 's|\\$|\\$|g'
}

quote_json() {
	sed -e 's|\\|\\\\|g' -e 's|\"|\\\"|g'
}

update_docker_host() {
	local PROF="$("$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=get name="$GITLAB_NAME")"
	PROF="$(echo "$PROF" | jq -c .data.profile | sed 's/{"key":"DB_HOST","value":"[^"]*"}/{"key":"DB_HOST","value":"'$DOCKER_HOST'"}/g')"
	# change host ip
	task_id=$("$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=set_start name="$GITLAB_NAME" profile="$PROF" | grep '"task_id"' | awk '{print $3}')
	while ! "$WEBAPI_BIN" --exec api=SYNO.Docker.Container version=1 method=set_status task_id="$task_id" | grep -q '"finished" : true'; do
		sleep 1
	done
}
