#!/bin/sh
# Copyright (c) 2000-2015 Synology Inc. All rights reserved.

. "$(dirname $0)"/common

DB_HOST="$DOCKER_HOST"
DB_USER="$PKG_SHORT"
API=/usr/syno/bin/synowebapi
SIZE_GITLAB=318
SIZE_REDIS=65

if [ "$SYNOPKG_PKG_STATUS" != UPGRADE ]; then
	HTTP_PORT="$pkgwizard_http_port"
	SSH_PORT="$pkgwizard_ssh_port"
	DB_NAME="$pkgwizard_db_name"
	DB_PASS="$(openssl rand -base64 48 | sed 's,/,_,g')"
	DB_SALT="$(openssl rand -base64 48 | sed 's,/,_,g')"
	MARIADB_PASS="${pkgwizard_mysql_password:+-p$pkgwizard_mysql_password}"
	HOSTNAME="$pkgwizard_hostname"
	ADMIN_EMAIL="$pkgwizard_admin_email"
	SMTP_ENABLE="$pkgwizard_smtp_enable"
	SMTP_ADDR="$pkgwizard_smtp_address"
	SMTP_PORT="$pkgwizard_smtp_port"
	SMTP_USER="$pkgwizard_smtp_user"
	SMTP_PASS="$pkgwizard_smtp_pass"
	SMTP_VERIFY="$pkgwizard_smtp_verify"
	SHARE="$pkgwizard_dataroot"
	SQL="CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASS'; CREATE DATABASE IF NOT EXISTS \`$(echo "$DB_NAME" | quote_sql)\` DEFAULT CHARACTER SET \`utf8\` COLLATE \`utf8_unicode_ci\`; GRANT ALL PRIVILEGES ON \`$(echo "$DB_NAME" | quote_sql)\`.* TO '$DB_USER'@'%';"

	echo "$SQL" | mysql -uroot "$MARIADB_PASS"

	(
		echo HTTP_PORT="\"$(echo "$HTTP_PORT" | quote_sh)\""
		echo SSH_PORT="\"$(echo "$SSH_PORT" | quote_sh)\""
		echo DB_NAME="\"$(echo "$DB_NAME" | quote_sh)\""
		echo DB_PASS="\"$(echo "$DB_PASS" | quote_sh)\""
		echo HOSTNAME="\"$(echo "$HOSTNAME" | quote_sh)\""
		echo ADMIN_EMAIL="\"$(echo "$ADMIN_EMAIL" | quote_sh)\""
		echo SMTP_ENABLE="\"$(echo "$SMTP_ENABLE" | quote_sh)\""
		echo SMTP_ADDR="\"$(echo "$SMTP_ADDR" | quote_sh)\""
		echo SMTP_PORT="\"$(echo "$SMTP_PORT" | quote_sh)\""
		echo SMTP_USER="\"$(echo "$SMTP_USER" | quote_sh)\""
		echo SMTP_PASS="\"$(echo "$SMTP_PASS" | quote_sh)\""
		echo SMTP_VERIFY="\"$(echo "$SMTP_VERIFY" | quote_sh)\""
		echo SHARE="\"$(echo "$SHARE" | quote_sh)\""
	) > "$ETC_PATH"/config
else
	. "$ETC_PATH"/config
fi

sed -i \
	-e "s/__HTTP_PORT__/$(echo "$HTTP_PORT" | quote_json | quote_sed)/g" \
	"$TARGET_PATH"/ui/config \
	"$GITLAB_PROFILE"
sed -i \
	-e "s/__SSH_PORT__/$(echo "$SSH_PORT" | quote_json | quote_sed)/g" \
	-e "s/__SHARE__/$(echo "$SHARE" | quote_json | quote_sed)/g" \
	-e "s/__DB_HOST__/$(echo "$DB_HOST" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__DB_NAME__/$(echo "$DB_NAME" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__DB_USER__/$(echo "$DB_USER" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__DB_PASS__/$(echo "$DB_PASS" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__DB_SALT__/$(echo "$DB_SALT" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__HOSTNAME__/$(echo "$HOSTNAME" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__ADMIN_EMAIL__/$(echo "$ADMIN_EMAIL" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__SMTP_ENABLE__/$(echo "$SMTP_ENABLE" | quote_json | quote_sed)/g" \
	-e "s/__SMTP_ADDR__/$(echo "$SMTP_ADDR" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__SMTP_PORT__/$(echo "$SMTP_PORT" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__SMTP_USER__/$(echo "$SMTP_USER" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__SMTP_PASS__/$(echo "$SMTP_PASS" | quote_sed | quote_json | quote_sed)/g" \
	-e "s/__SMTP_VERIFY__/$([ "$SMTP_VERIFY" = true ] && echo peer || echo none)/g" \
	"$GITLAB_PROFILE"

/var/packages/Docker/target/tool/helper \
	redis 3.0.7 "$TARGET_PATH"/docker/redis-3.0.7.tar.xz $SIZE_REDIS \
	sameersbn/gitlab 8.11.5 "$TARGET_PATH"/docker/gitlab-8.11.5.tar.xz $SIZE_GITLAB \
	|| exit 1

$API --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false \
	profile="$(cat "$REDIS_PROFILE")"
$API --exec api=SYNO.Docker.Container version=1 method=create is_run_instantly=false \
	profile="$(cat "$GITLAB_PROFILE")"

exit 0
